### ISSUE TITLE
Component error: device-tracker - Integration device-tracker not found. (home-assistant v0.98.5)

### ISSUE THREAD

**Issue by palica** [j1nx/homeassistant-phonetrack#1]
Hello,

I am getting the error message from title when running "Check config" and this notice upon start up:

```
Invalid config

The following components and platforms could not be set up:
    device-tracker
Please check your config.
```

Here is my config:
```
device-tracker:   
  - platform: phonetrack
    url: https://cloud.my.cloud/index.php/apps/phonetrack/api/getlastpositions/
    token: xx23xx82exxeexx7exx28xx20xxd4xxx
  
    devices:
    - My-device
```

I have copied the files to custom_components direcotry under /usr/share/hassio/homeassistant

Is the component working correctly with latest HA? I have read somewhere in the developer manuals that the component has to define DOMAIN variable. 

Please let me know if I am doing anything wrong.
Thanks for help.
