### ISSUE TITLE
Integration doesn't seem to be working anymore

### ISSUE THREAD

**Issue by Sjorsa1** [j1nx/homeassistant-phonetrack#2]
I get the following errors when starting up homeassistant with this integration:

```
2020-07-12 16:12:52 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 76, in async_setup_legacy
discovery_info,
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/phonetrack/device_tracker.py", line 33, in setup_scanner
PhoneTrackDeviceTracker(hass, config, see)
File "/config/custom_components/phonetrack/device_tracker.py", line 50, in __init__
self._update_info()
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/phonetrack/device_tracker.py", line 61, in _update_info
data = data[self.token]
TypeError: list indices must be integers or slices, not str```

Is there anything I can do to fix this?

**Comment by jonas-w** [comment]
@Sjorsa1 and maybe others that see this issue. This error occurs when your token is wrong as the phonetrack API returns an empty list `[]` when the token does not exist.
You can test this yourself by navigating to the url `https://<nextcloud-domain>/index.php/apps/phonetrack/api/getlastpositions/<your token>` and it should return a json object like (I replaced all values of mine with 0):
```json
{
  "<token>": {
    "<device_name>": {
      "useragent": "PhoneTrack/0.0",
      "lat": 0.0,
      "lon": 0.0,
      "timestamp": 0,
      "batterylevel": 0,
      "satellites": 0,
      "accuracy": 0,
      "altitude": 0,
      "speed": 0.0,
      "bearing": 0.0
    }
  }
}
```

**Comment by GAS85** [comment]
Just for information, this automation can be replaced with existing functionality. E.g. in `configuration.yaml` add this:

```yaml
sensor:
  - platform: rest
    name: Car Location
    # Replace `b22...9e` with your actual ID
    # Replace `car` with your actual Attribute name
    json_attributes_path: "$.[b22...9e].car"
    json_attributes:
      - lat
      - lon
      - accuracy
      - batterylevel
    # Replace `b22...9e` with your actual ID
    # Replace with the URL where your JSON is hosted
    resource: "https://<FQDN>/index.php/apps/phonetrack/api/getlastpositions/b22...9e"
    # Replace `b22...9e` with your actual ID
    # Replace `car` with your actual Attribute name
    value_template: "{{ value_json.b22...9e.car }}"
```

And add automation to periodically fetch the data:

```yaml
alias: "[Phonetrack] Fetch Car Location Every 15 Minutes"
description: "This automation will periodically call REST API of Nextcloud phonetrack and fetch Geodata if possible"
triggers:
  - minutes: /15
    trigger: time_pattern
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.car_location
  - action: device_tracker.see
    metadata: {}
    data:
      # Replace `car` with your actual Attribute name
      host_name: car
      gps:
        - "{{ state_attr('sensor.car_location', 'lat') }}"
        - "{{ state_attr('sensor.car_location', 'lon') }}"
      dev_id: bmw
      gps_accuracy: "{{ state_attr('sensor.car_location', 'accuracy') | default(0) | int }}"
```
